[package]
name = "zkp-rust-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = {version="1.0.2", features = ["abigen", "rustls", "ws"] }
tokio = "1.25.0"
eyre = "0.6.8"